url: https://auroraspace.github.io
baseurl:


# Site settings
title: Aurora Space Projects
email: auroraspace@gmail.com
description: "Aurora Space Projects. We are a company specialized in small satellites projects and flight software development."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 182B3A
  secondary: 3A827E
  secondary-dark: 1C3F55

# Team names, titles and social links
people:
- name: Carlos González
  pic: cgonzalez
  position: Co-Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Tomás Opazo
  pic: topazo
  position: Co-Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Alex Becerra
  pic: abecerra
  position: Co-Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Felipe Troncoso
  pic: ftroncoso
  position: Co-Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Camilo Rojas
  pic: crojas
  position: Co-Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sebastian Derteano
  pic: sderteano
  position: Co-Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/auroraspaceproj
  - title: facebook
    url: #
  - title: github
    url: http://github.com/auroraspace

# Postal address (add as many lines as necessary)
address:
  - line: Santiago
  - line: Chile

# Build settings
markdown: kramdown
permalink: pretty